USE eggland_bangladesh;
ALTER TABLE delivery_items MODIFY qty INT NOT NULL DEFAULT 0;
ALTER TABLE demands MODIFY total_qty INT NOT NULL DEFAULT 0;
ALTER TABLE demand_items MODIFY qty INT NOT NULL DEFAULT 0;
ALTER TABLE dispatches MODIFY qty_dispatched INT NOT NULL DEFAULT 0;
ALTER TABLE inventory MODIFY qty_available INT NOT NULL DEFAULT 0;
ALTER TABLE lot_items MODIFY qty INT NOT NULL DEFAULT 0;
ALTER TABLE order_items MODIFY qty INT NOT NULL DEFAULT 0;
ALTER TABLE warehouse_lots MODIFY qty INT NOT NULL DEFAULT 0;
